# Generated by Django 4.1.7 on 2023-04-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('is_admin', models.BooleanField()),
            ],
        ),
    ]
